version: '3'

services:
  db:
    image: postgres:16
    expose:
      - "${DB_PORT}"
    #volumes:
    ports:
      - "5432:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
