server:
    port: 8000
    error:
        path: "/error"

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: off
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui